// Generated by CoffeeScript 1.6.3
(function() {
  var App;

  App = Ember.Application.create();

  console.log(chrome);

  App.Router.map(function() {});

  App.IndexRoute = Ember.Route.extend({
    model: function() {
      return ["red", "yellow", "blue", "yolo"];
    }
  });

  chrome.runtime.onMessage.addListener(function(request, sender, sendResponse) {
    console.log(request.url);
    return $.ajax({
      url: "http://readahead.herokuapp.com/links.json",
      type: "POST",
      data: {
        url: request.url
      },
      dataType: "json",
      success: function(data) {
        return console.log(data);
      }
    });
  });

}).call(this);
