// Generated by CoffeeScript 1.3.3
(function() {
  var onClick;

  onClick = function() {
    console.log('sending message', chrome);
    return chrome.tabs.query({}, function(tabs) {
      var i, message, _results;
      message = {
        greeting: "hello"
      };
      i = 0;
      _results = [];
      while (i < tabs.length) {
        chrome.tabs.sendMessage(tabs[i].id, message);
        _results.push(++i);
      }
      return _results;
    });
  };

  chrome.contextMenus.create({
    title: "Add to my readahead list",
    onclick: onClick
  });

}).call(this);
