// Generated by CoffeeScript 1.3.3
(function() {
  var sendMessage;

  sendMessage = function(tabId, url) {
    return chrome.tabs.sendMessage(tabId, {
      url: url
    });
  };

  chrome.contextMenus.create({
    title: "Add this page to readahead",
    contexts: ["page"],
    onclick: function(info, tab) {
      return sendMessage(tab.id, tab.url);
    }
  });

  chrome.contextMenus.create({
    title: "Add this link to readahead",
    onclick: function(info, tab) {
      return sendMessage(tab.id, info.linkUrl);
    },
    contexts: ["link"]
  });

}).call(this);
